Grocery/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls'), name='user'),
    path('shop/', include('shop.urls'), name='shop'),
    path('', RedirectView.as_view(url=reverse_lazy('shop:index'))),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views


app_name = 'shop'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('detail/<slug:pk>', views.Detail.as_view(), name='detail'),
    path('cart/', views.Cart.as_view(), name='cart'),
    path('addcart/', views.AddCart.as_view(), name='addcart'),
    path('check/', views.Check.as_view(), name='check'),
    path('clear/', views.Clear.as_view(), name='clear'),
]

shop/models.py
from django.db import models
from django.contrib.auth.views import get_user_model
from django.urls import reverse

# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=254)
    price = models.IntegerField()
    description = models.TextField()
    img = models.ImageField(upload_to='product_img')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_absolute_url(self):
        return reverse('shop:detail', kwargs={'pk': self.pk})


class ShoppingCart(models.Model):
    product = models.ManyToManyField('shop.OrderCard', null=True, related_name='cardorders')
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    order_cards = models.ManyToManyField('shop.OrderCard', blank=True)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'Cart'
        verbose_name_plural = 'Carts'


class OrderCard(models.Model):
    product = models.ForeignKey(Product, verbose_name='产品', on_delete=models.CASCADE)
    amount = models.IntegerField(verbose_name='数量', default=0)


class Order(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    create_time = models.DateTimeField(auto_now_add=True)
    order_card = models.ManyToManyField(OrderCard)
    total = models.IntegerField()

shop/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.base import View
from django.contrib import messages

from .models import Product, OrderCard, Order


class Index(ListView):
    template_name = 'shop/index.html'
    paginate_by = 10

    def get_queryset(self):
        return Product.objects.all().order_by('id')


class Detail(DetailView):
    template_name = 'shop/detail.html'
    model = Product


class Cart(LoginRequiredMixin, ListView):
    template_name = 'shop/cart.html'

    def get_queryset(self):
        return self.request.user.shoppingcart.product.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(Cart, self).get_context_data()
        object_list = context['object_list']
        num = 0
        for i in object_list:
            num += i.product.price * i.amount
        context['total'] = num
        return context


class AddCart(LoginRequiredMixin, View):
    def post(self, request):
        # 获取产品， 购物车
        product = self.request.POST.get('product')
        product_obj = Product.objects.get(pk=product)
        shopping_card = request.user.shoppingcart
        try:
            order_card = OrderCard.objects.get(cardorders=shopping_card, product=product)
        except OrderCard.DoesNotExist:
            order_card = OrderCard.objects.create(product=product_obj)
            shopping_card.product.add(order_card)
            shopping_card.save()

        # 数量加1
        order_card.amount += 1
        order_card.save()

        messages.success(request, 'Product %s AddToCart Successfully' % product_obj.name)
        return redirect(reverse('shop:detail', kwargs={'pk': product}))


class Check(View):
    def post(self, request):
        user = request.user
        total = int(request.POST.get('total'))
        if not user.shoppingcart.product.all().exists():
            messages.error(request, '无商品')
            return redirect('shop:cart')
        if user.wallet.amount >= total:
            user.wallet.amount -= total
            user.wallet.save()
            order = Order.objects.create(user=user, total=total)
            for i in user.shoppingcart.product.all():
                product_order = OrderCard.objects.create(product=i.product, amount=i.amount)
                order.order_card.add(product_order)
            user.shoppingcart.product.all().delete()
            user.shoppingcart.paid = True
            user.shoppingcart.save()
            print(order.order_card.all())
            messages.success(request, 'checkout success')
        else:
            messages.error(request, 'fail to checkout， no enough money!')
        return redirect('shop:cart')


class Clear(View):
    def get(self, request):
        request.user.shoppingcart.product.all().delete()
        return redirect('shop:cart')

templates/shop/base.html
{% load static  %}
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/uikit.min.css' %}" />
    <script src="{% static 'js/uikit.js' %}"></script>
    <script src="{% static 'js/uikit-icons.min.js' %}"></script>
</head>

<body class="uk-background-muted">
{% include 'components/navbar.html' %}

{% block main %}

{% endblock %}

{% include 'components/footer.html' %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
        <script>
    UIkit.notification({message: "<span uk-icon='icon: check'></span> {{ message}}", status: 'success'})
        </script>
    {% endfor %}
</ul>
{% endif %}

</body>

</html>

templates/shop/cart.html
{% extends 'shop/base.html' %}

{% block title %}
Cart
{% endblock %}

{% block main %}
    <div class="uk-container">
<div class="uk-card uk-card-default uk-card-body" style="min-height: 800px">
                            <h3 class="uk-card-title">Your Cart</h3>
                            <ul class="uk-list uk-list-divider">
                                {% for i in object_list %}
                                <li class="uk-flex">
                                    <div>
                                        <h5 class="uk-margin-remove-bottom">{{ i.product.name }} * {{ i.amount }}</h5>
                                        <span class="uk-text-small">{{ i.product.description }}</span>
                                    </div>
                                    <div class="uk-margin-auto-left uk-text-right">{% widthratio i.product.price 1 i.amount %}</div>
                                </li>
                                {% endfor %}
                                <li class="uk-text-bold uk-text-emphasis">
                                    <span class="">Total(Dollar)</span>
                                    <div class="uk-float-right">${{ total }}</div>
                                </li>
                            </ul>
    <form action="{% url 'shop:check' %}" method="post">{% csrf_token %}
        <input type="hidden" value="{{ total }}" name="total">
    <button class="uk-button uk-button-primary" type="submit">Check</button>
        <button class="uk-button uk-button-primary" type="button" onclick="window.location.href='{% url 'shop:clear' %}'">Clear</button>
            </form>

                        </div>

    </div>
{% endblock %}

templates/shop/detail.html
{% extends 'shop/base.html' %}

{% block title %}
Product Detail
{% endblock %}

{% block main %}

    <div class="uk-container" style="min-height: 800px">

    <h2>Product: {{ object.name }}</h2>
        <hr>
        <img src="/media/{{ object.img }}" alt="" style="height: 300px; width: 300px">
        <hr>
    <p>Description: {{ object.description }}</p>
        <p>Price:{{ object.price }}</p>
        <hr>
        <form action="{% url 'shop:addcart' %}" method="post">{% csrf_token %}
            <input type="hidden" value="{{ object.pk }}" name="product">
    <button class="uk-button uk-button-primary" type="submit">AddToCart</button>
            </form>
</div>
{% endblock %}

templates/shop/index.html
{% extends 'shop/base.html' %}

{% block title %}
首页
{% endblock %}

{% block main %}


<div class="uk-container" style="min-height: 800px">
<div class="uk-child-width-1-1 uk-child-width-1-4" uk-grid>

    {% for i in page_obj %}
            <div>
                <div class="uk-card uk-card-default tm-image-card uk-card-hover" onclick="window.location.href='{{ i.get_absolute_url }}'">
                    <div class="uk-card-media-top">
                        <img src="/media/{{ i.img }}" alt="" style="height: 250px">
                    </div>
                    <div class="uk-card-body">
                        <h3 class="uk-card-title">{{ i.name }}</h3>
                        <p>{{ i.description|slice:":10" }}</p>
                    </div>
                </div>
            </div>
    {% endfor %}
        </div>
</div>


{% endblock %}