Grocery/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls'), name='user'),
    path('shop/', include('shop.urls'), name='shop'),
    path('', RedirectView.as_view(url=reverse_lazy('shop:index'))),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views


app_name = 'shop'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('detail/<slug:pk>', views.Detail.as_view(), name='detail'),
    path('cart/', views.Cart.as_view(), name='cart'),
    path('addcart/', views.AddCart.as_view(), name='addcart'),
    path('check/', views.Check.as_view(), name='check'),
    path('clear/', views.Clear.as_view(), name='clear'),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('register/', views.Register.as_view(), name='register'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('userinfo/', views.UserInfo.as_view(), name='userinfo'),
]

templates/components/footer.html
<div class="uk-section uk-section-primary uk-padding-remove-bottom uk-padding-remove-top">
    <div class="uk-container uk-text-center">
        <hr class="uk-margin-remove-bottom uk-margin-medium-top">
        <div class="uk-margin-top uk-margin-bottom">
            <div uk-grid="" class="uk-child-width-auto@m uk-flex-middle uk-grid">
                <div class="uk-first-column">
                </div>
                <div class="uk-margin-auto">
                    <div>Team: ISQA3900-GROUP5 Contact: HangchengZhang YuGuo</div>
                </div>
                <div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/components/navbar.html
{% load static %}
<div uk-sticky="show-on-up: true; animation: uk-animation-slide-top; sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky; cls-inactive: uk-navbar-transparent;">
    <nav class="uk-navbar-container uk-visible@m" uk-navbar>
        <div class="uk-navbar-left">
            <a href="" class="uk-navbar-item uk-logo">
                <img src="{% static 'img/logo.png' %}" style="height: 40px" alt="">
            </a>

            <ul class="uk-navbar-nav">
                <li class="uk-active"><a href="{% url 'shop:index' %}">all products</a></li>
                <li>
                    <a href="javascript:;">User</a>
                    <div class="uk-navbar-dropdown">
                        <ul class="uk-nav uk-navbar-dropdown-nav">
                            <li><a href="{% url 'user:userinfo' %}">UserInfo</a></li>
                            <li><a href="{% url 'shop:cart' %}">Cart</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>

        <div class="uk-navbar-right">
            <div>
                <a class="uk-navbar-toggle" href="#" uk-search-icon></a>
                <div class="uk-drop" uk-drop="mode: click; pos: left-center; offset: 0">
                    <div class="uk-grid-small uk-flex-middle" uk-grid>
                        <div class="uk-width-expand">
                            <form class="uk-search uk-search-navbar uk-width-1-1">
                                <input class="uk-search-input" type="search" placeholder="Search..." autofocus>
                            </form>
                        </div>
                        <div class="uk-width-auto">
                            <a class="uk-navbar-dropdown-close" href="#" uk-close></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="uk-navbar-item uk-visible@l">
                {% if not request.user.is_authenticated %}
                <button class="uk-button uk-button-text" onclick="window.location.href='{% url 'user:login' %}'">Login</button>
                <a class="uk-button uk-button-primary uk-margin-small-left uk-border-pill" href="{% url 'user:register' %}">Register</a>
                    {% else %}
                    <button class="uk-button uk-button-text">{{ request.user.username }}</button>
                <a class="uk-button uk-button-primary uk-margin-small-left uk-border-pill" href="{% url 'user:logout' %}">Logout</a>
                {% endif %}
            </div>
        </div>
    </nav>
</div>